language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - "pip install .[develop]"
# command to run tests
script: python setup.py test
