language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - "pip install -U pip"
  - "pip --version"
  - "pip install .[develop]"
  - "pip install pytest-cov coveralls"
# command to run tests
script: python setup.py test --addopts "-vv --cov bloomsky_api"
after_success: coveralls
